ITEM_ID="webserver"
ITEM_LABEL="Webserver"

DEFAULT_SYSTEM_UPDATE=1
DEFAULT_BASE_PACKAGES=1
DEFAULT_PYTHON_STACK=1
DEFAULT_UFW=1
DEFAULT_FAIL2BAN=1
DEFAULT_SSH_KEY_CHECK=1
DEFAULT_DOCKER=0
DEFAULT_TAILSCALE=0
DEFAULT_SET_HOSTNAME=1
DEFAULT_SET_TIMEZONE=1
DEFAULT_SSH_HARDENING=0
