ITEM_ID="minimal-custom"
ITEM_LABEL="Minimal / Benutzerdefiniert"

DEFAULT_SYSTEM_UPDATE=0
DEFAULT_BASE_PACKAGES=0
DEFAULT_PYTHON_STACK=0
DEFAULT_UFW=0
DEFAULT_FAIL2BAN=0
DEFAULT_SSH_KEY_CHECK=0
DEFAULT_DOCKER=0
DEFAULT_TAILSCALE=0
DEFAULT_SET_HOSTNAME=0
DEFAULT_SET_TIMEZONE=0
DEFAULT_SSH_HARDENING=0
