ITEM_ID="python-dev"
ITEM_LABEL="Python Dev"

DEFAULT_SYSTEM_UPDATE=1
DEFAULT_BASE_PACKAGES=1
DEFAULT_PYTHON_STACK=1
DEFAULT_UFW=0
DEFAULT_FAIL2BAN=0
DEFAULT_SSH_KEY_CHECK=0
DEFAULT_DOCKER=0
DEFAULT_TAILSCALE=0
DEFAULT_SET_HOSTNAME=0
DEFAULT_SET_TIMEZONE=1
DEFAULT_SSH_HARDENING=0
